# Generated by Django 4.2.7 on 2024-03-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slr.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slr', '0002_csvfile_delete_csvrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to=slr.models.user_directory_path),
        ),
    ]
